CREATE TABLE public.users (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NOT NULL,
	"email" varchar NOT NULL,
	"password" varchar NOT NULL,
	created_date timestamp NOT NULL,
	modified_date timestamp NOT NULL,
	active boolean NOT NULL
);

ALTER TABLE public.users ADD CONSTRAINT users_id_pk PRIMARY KEY (id);
ALTER TABLE public.users ALTER COLUMN modified_date SET DEFAULT now();
ALTER TABLE public.users ALTER COLUMN active SET DEFAULT true;
ALTER TABLE public.users ADD CONSTRAINT users_email_un UNIQUE (email);
