CREATE TABLE public.users (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NOT NULL,
	"email" varchar NOT NULL,
	"password" varchar NOT NULL,
	created_date timestamp NOT NULL,
	modified_date timestamp NOT NULL,
	active boolean NOT NULL
);

ALTER TABLE public.users ADD CONSTRAINT users_id_pk PRIMARY KEY (id);
ALTER TABLE public.users ALTER COLUMN modified_date SET DEFAULT now();
ALTER TABLE public.users ALTER COLUMN active SET DEFAULT true;
ALTER TABLE public.users ADD CONSTRAINT users_email_un UNIQUE (email);



CREATE TABLE public.shortcuts (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	shortlink varchar NOT NULL,
	url varchar NOT NULL,
	description varchar NULL,
	created_date timestamp NOT NULL,
	modified_date timestamp NOT NULL DEFAULT now(),
	active boolean NOT NULL DEFAULT true,
	userid int NOT NULL,
	CONSTRAINT shortcuts_pk PRIMARY KEY (id),
	CONSTRAINT shortcuts_un UNIQUE (shortlink,userid),
	CONSTRAINT shortcuts_fk FOREIGN KEY (userid) REFERENCES public.users(id)
);

ALTER TABLE public.shortcuts RENAME COLUMN userid TO user_id;
